### ISSUE TITLE
TACLS seems to save/load config data on most scene changes

### ISSUE THREAD

**Issue by SkyMarshal** [taraniselsu/TacLifeSupport#77] opened 2015-06-28 00:33 UTC

**Comment by taraniselsu** [comment] 2015-12-09 02:34
It should on every scene change. That is how KSP works internally. I will reduce the log spam though.

**Comment by taraniselsu** [comment] 2015-12-09 02:35
Oops, meant to mark as a duplicate of #79

**Closed by taraniselsu** 2015-12-09 02:34 UTC
